# LabelEncoder OrdinalEncoder OneHotEncoder SimpleEmputer

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

# Ordinal Encoding

In [2]:
X = [['Male'], ['Female']]
X

[['Male'], ['Female']]

In [3]:
oe = OrdinalEncoder()

In [4]:
x = oe.fit_transform(X)

In [5]:
x

array([[1.],
       [0.]])

In [6]:
Y = [['male'], ['female'], ['Others']]
Y

[['male'], ['female'], ['Others']]

In [7]:
y = oe.fit_transform(Y)
y

array([[2.],
       [1.],
       [0.]])

# Simple Imputer

In [8]:
# from sklearn.preprocessing import SimpleImputer

# LabelEncoder

In [9]:
A = ['High', 'Medium','Very High', 'Low', 'Very Low']
A

['High', 'Medium', 'Very High', 'Low', 'Very Low']

In [10]:
le = LabelEncoder()
a = le.fit_transform(A)
a

array([0, 2, 3, 1, 4], dtype=int64)

# OneHotEncoder

In [11]:
ohe = OneHotEncoder(drop = 'first')

In [12]:
B = [['North'], ['South'], ['West'], ['East']]
B

[['North'], ['South'], ['West'], ['East']]

In [13]:
b = ohe.fit_transform(B).toarray()
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [14]:
df = pd.DataFrame(b, columns = ['South', 'West', 'East'], index = ['South', 'West', 'East', 'North'])
df

South  West  East
South    1.0   0.0   0.0
West     0.0   1.0   0.0
East     0.0   0.0   1.0
North    0.0   0.0   0.0