In [1]:
import pickle
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [2]:
sex = pickle.load(open('model/sex.pkl', 'rb'))
ecg = pickle.load(open('model/ECG.pkl', 'rb'))
slope = pickle.load(open('model/slope.pkl', 'rb'))
chest = pickle.load(open('model/chest.pkl', 'rb'))
exercise = pickle.load(open('model/exercise.pkl', 'rb'))

In [3]:
rf = pickle.load(open('heart.pkl', 'rb'))
rf

RandomForestClassifier(max_features=90, max_leaf_nodes=200, n_jobs=-1,
                       oob_score=True, random_state=80)

In [4]:
X_test = pickle.load(open('train.pkl', 'rb'))
X_test.head()

Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
427   59  1.0            0.0        140            0          0         2.0   
319   68  1.0            0.0        145            0          1         1.0   
705   59  1.0            1.0        140          221          0         1.0   
186   58  1.0            1.0        130          251          0         1.0   
519   63  1.0            0.0         96          305          0         2.0   

     MaxHR  ExerciseAngina  Oldpeak  ST_Slope  
427    117             1.0      1.0       1.0  
319    136             0.0      1.8       2.0  
705    164             1.0      0.0       2.0  
186    110             0.0      0.0       2.0  
519    121             1.0      1.0       2.0

In [5]:
X_test.head(1)

Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
427   59  1.0            0.0        140            0          0         2.0   

     MaxHR  ExerciseAngina  Oldpeak  ST_Slope  
427    117             1.0      1.0       1.0

In [6]:
result = rf.predict(X_test.head(1))

In [7]:
print(result)

[1]


In [8]:
test = np.array([40, 'M', 'ATA', 140, 289, 0, 'Normal', 172, 'N', 0, 'Up'], dtype = object).reshape(1, 11)
# 40	M	ATA	140	289	0	Normal	172	N	0.0	Up	

In [9]:
test

array([[40, 'M', 'ATA', 140, 289, 0, 'Normal', 172, 'N', 0, 'Up']],
      dtype=object)

In [10]:
test[:, 1]

array(['M'], dtype=object)

In [11]:
ecg

OrdinalEncoder(categories=[['LVH', 'Normal', 'ST']])

In [12]:
slope

OrdinalEncoder(categories=[['Down', 'Flat', 'Up']])

In [13]:
chest

OrdinalEncoder(categories=[['ASY', 'ATA', 'NAP', 'TA']])

In [14]:
exercise

OrdinalEncoder(categories=[['N', 'Y']])

In [15]:
test_sex = sex.fit_transform(test[:, 1].reshape(1, 1))
test_sex

array([[1.]])

In [16]:
chest_test = chest.fit_transform(test[:, 2].reshape(1, 1))
chest_test

array([[1.]])

In [17]:
ecg_test = ecg.fit_transform(test[:, 6].reshape(1, 1))

In [18]:
ecg_test

array([[1.]])

In [19]:
exercise_test = exercise.fit_transform(test[:, 8].reshape(1, 1))
exercise_test

array([[0.]])

In [20]:
slope_test = slope.fit_transform(test[:, 10].reshape(1, 1))
slope_test

array([[2.]])

In [21]:
test[:, [1, 2, 6, 8, 10]]

array([['M', 'ATA', 'Normal', 'N', 'Up']], dtype=object)

In [22]:
test[:, [0, 3, 4, 5, 7, 9]]

array([[40, 140, 289, 0, 172, 0]], dtype=object)

In [72]:
# Age	Sex	ChestPainType	RestingBP	Cholesterol	FastingBS	RestingECG	MaxHR	ExerciseAngina	Oldpeak	ST_Slope

In [88]:
dataset = np.concatenate((test[:, [0]], test_sex, chest_test,test[:, [3]], test[:, [4]], test[:, [5]], ecg_test, test[:, [7]], exercise_test, test[:, [9]], slope_test), axis= 1)

In [89]:
dataset

array([[40, 1.0, 1.0, 140, 289, 0, 1.0, 172, 0.0, 0, 2.0]], dtype=object)

In [90]:
rf.predict(dataset)

C:\Users\Abhisek\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)