In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
import numpy as np
from matplotlib import pyplot as plt

In [2]:
digits = load_digits()

In [3]:
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [4]:
from sklearn.model_selection import cross_val_score

In [5]:
cross_val_score(LogisticRegression(), digits.data, digits.target)

C:\Users\Sikkim\AppData\Roaming\Python\Python310\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Sikkim\AppData\Roaming\Python\Python310\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [6]:
cross_val_score(SVC(), digits.data, digits.target, cv = 5) # CV = NO. of Folds

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [7]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target)

array([0.92222222, 0.90833333, 0.95264624, 0.95821727, 0.93314763])

In [8]:
score1 = cross_val_score(RandomForestClassifier(n_estimators=5), digits.data, digits.target)
np.average(score1)

0.8670256886412876

In [9]:
score2 = cross_val_score(RandomForestClassifier(n_estimators=20), digits.data, digits.target)
np.average(score2)

0.9204348498916743

In [10]:
score3 = cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target)
np.average(score3)

0.9315722686474774